module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2024: true,
    node: true,
  },
  extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  rules: {
    'accessor-pairs': 'error',
    camelcase: 'warn',
    'consistent-return': 'error',
    curly: 'error',
    'default-param-last': 'error',
    'dot-notation': 'warn',
    eqeqeq: 'error',
    'guard-for-in': 'warn',
    'init-declarations': ['error', 'always'],
    'logical-assignment-operators': ['error', 'always'],
    'max-classes-per-file': ['error', { 'ignoreExpressions': true, 'max': 2 }],
    'max-depth': ['error', 3],
    'no-duplicate-imports': 'warn',
    'no-else-return': 'warn',
    'no-multi-assign': 'error',
    'no-negated-condition': 'warn',
    'no-return-assign': 'error',
    'no-sequences': 'error',
    'no-unreachable-loop': 'error',
    'no-var': 'error',
    'require-atomic-updates': 'error',
    'spaced-comment': ['error', 'always'],
    'array-bracket-newline': ['error', { 'multiline': true }],
    'array-element-newline': ['error', 'consistent'],
    'arrow-spacing': 'error',
    'block-spacing': 'error',
    'comma-spacing': ['error', { 'before': false, 'after': true }],
    'eol-last': ['error', 'always'],
    'function-paren-newline': ['error', 'consistent'],
    indent: ['error', 2],
    'no-trailing-spaces': 'error',
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'sort-imports': 'error',
    'no-multi-spaces': 'error',
    'no-multiple-empty-lines': 'error',
    'comma-dangle': ['error', { objects: 'always-multiline' }],
    'space-before-blocks': 'error',
    'object-curly-newline': ['error', { 'multiline': true }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'no-extra-parens': 'error',
    'no-whitespace-before-property': 'error',
    'rest-spread-spacing': ['error'],
    'semi-spacing': 'error',
    'template-curly-spacing': ['error', 'always'],
  },
};
